# This file was generated by GoReleaser. DO NOT EDIT.
cask "apisniff" do
  version "0.12.6"

  on_macos do
    on_intel do
      sha256 "f88319f6a676f3de246181af51cec20fca8d03bade7277287ffa3e38d62ae47d"
      url "https://github.com/4LAU/apisniff/releases/download/v#{version}/apisniff_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/4LAU/apisniff/"
    end
    on_arm do
      sha256 "8bd1084bc7b1230830e5cac341f3ff54f78d77e5be3ef1c78b5c87ba3e04c48c"
      url "https://github.com/4LAU/apisniff/releases/download/v#{version}/apisniff_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/4LAU/apisniff/"
    end
  end

  on_linux do
    on_intel do
      sha256 "450926abcef11460330ec45d084a4d2986a7d91a412f75810b1daa11f40918ce"
      url "https://github.com/4LAU/apisniff/releases/download/v#{version}/apisniff_#{version}_linux_amd64.tar.gz",
        verified: "github.com/4LAU/apisniff/"
    end
    on_arm do
      sha256 "199db6d13c8e362dd8ce7146034db47d4cf51db0584d0e3a9cf5e67296a6fc30"
      url "https://github.com/4LAU/apisniff/releases/download/v#{version}/apisniff_#{version}_linux_arm64.tar.gz",
        verified: "github.com/4LAU/apisniff/"
    end
  end

  name "apisniff"
  desc "API recon: preflight defenses, traffic capture, and spec extraction"
  homepage "https://github.com/4LAU/apisniff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apisniff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apisniff"]
    end
  end

  # No zap stanza required

end
