# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apisniff < Formula
  desc "API recon: preflight defenses, traffic capture, and spec extraction"
  homepage "https://github.com/4LAU/apisniff"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/4LAU/apisniff/releases/download/v0.10.0/apisniff_0.10.0_darwin_amd64.tar.gz"
      sha256 "72681588de3791b0a122ed4427466289807a84d2435bff84e3d0c5a4fddc6a5d"

      define_method(:install) do
        bin.install "apisniff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/4LAU/apisniff/releases/download/v0.10.0/apisniff_0.10.0_darwin_arm64.tar.gz"
      sha256 "ad6e0416e588de01dc382fa7e4827d4cf3ea166137111d82f48d34469005ba1c"

      define_method(:install) do
        bin.install "apisniff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/4LAU/apisniff/releases/download/v0.10.0/apisniff_0.10.0_linux_amd64.tar.gz"
      sha256 "6a3ed9003cad7d45ed16891875d3e893580959db7305e4e4505b32dbe37af50a"
      define_method(:install) do
        bin.install "apisniff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/4LAU/apisniff/releases/download/v0.10.0/apisniff_0.10.0_linux_arm64.tar.gz"
      sha256 "fa011ee4af09f5ee5c83e1982c3ae6fdda4bf530f3bad14927dd0feb0d794d49"
      define_method(:install) do
        bin.install "apisniff"
      end
    end
  end

  test do
    assert_match "Usage", shell_output("#{bin}/apisniff --help")
  end
end
