# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apisniff < Formula
  desc "API recon: preflight defenses, traffic capture, and spec extraction"
  homepage "https://github.com/4LAU/apisniff"
  version "0.12.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/4LAU/apisniff/releases/download/v0.12.5/apisniff_0.12.5_darwin_amd64.tar.gz"
      sha256 "979dd2fbe896c5dd696da64eec254d1db7a98834da5d7cb0a7a6d2f3cd86a449"

      define_method(:install) do
        bin.install "apisniff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/4LAU/apisniff/releases/download/v0.12.5/apisniff_0.12.5_darwin_arm64.tar.gz"
      sha256 "c0590f15028963baa01fe53c7ba5f009d2723317d4f884f3ffd5a63b026d1213"

      define_method(:install) do
        bin.install "apisniff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/4LAU/apisniff/releases/download/v0.12.5/apisniff_0.12.5_linux_amd64.tar.gz"
      sha256 "95f3be2ad57e7908d5f10dc453728d9295f3037300871d89ac43f48a239cec02"
      define_method(:install) do
        bin.install "apisniff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/4LAU/apisniff/releases/download/v0.12.5/apisniff_0.12.5_linux_arm64.tar.gz"
      sha256 "38c20b09b3486cc94323fd3e85ec5e67f485147b44f58a9a27388adf25fff90c"
      define_method(:install) do
        bin.install "apisniff"
      end
    end
  end

  test do
    assert_match "Usage", shell_output("#{bin}/apisniff --help")
  end
end
