# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apisniff < Formula
  desc "API recon: preflight defenses, traffic capture, and spec extraction"
  homepage "https://github.com/4LAU/apisniff"
  version "0.12.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/4LAU/apisniff/releases/download/v0.12.2/apisniff_0.12.2_darwin_amd64.tar.gz"
      sha256 "3f83e6d705c502ffda809d4430ab83afad42a879c782e3fc7fe58b1e1b322242"

      define_method(:install) do
        bin.install "apisniff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/4LAU/apisniff/releases/download/v0.12.2/apisniff_0.12.2_darwin_arm64.tar.gz"
      sha256 "acc826235381e8ad36775939081cec5b78f79a4d398d71167ff94967774d12dd"

      define_method(:install) do
        bin.install "apisniff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/4LAU/apisniff/releases/download/v0.12.2/apisniff_0.12.2_linux_amd64.tar.gz"
      sha256 "c3f4f32ddf3cef2bb27177b9e4720044052a7453cc9143e2ef4826643668625b"
      define_method(:install) do
        bin.install "apisniff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/4LAU/apisniff/releases/download/v0.12.2/apisniff_0.12.2_linux_arm64.tar.gz"
      sha256 "04cb46793b005741f1717956d836cd7db25b1f594ef393b50f07a922207fd8bc"
      define_method(:install) do
        bin.install "apisniff"
      end
    end
  end

  test do
    assert_match "Usage", shell_output("#{bin}/apisniff --help")
  end
end
